% Solar Gpositive-restricted data analysis using fourier models
%% Startup
clear 
clc
close all

df = caricaSolar(); % nota: la funzione deve essere aggiunta al path di matlab

Td=2*24;
Ty=365;

% positive generation selection
pgen=df.Generation>0; % positive generation locatio 
sel=any([circshift(pgen, 1), circshift(pgen, -1)], 2); % all conditions here
wmax = sum(df.Generation==0); % max weigth, number of zeroes values
weigths = wmax*sel - (wmax-1)*pgen;

% select data
data = df(sel, :);
weigths = weigths(sel);

phifun=@(instances, periods)[
    instances.^0 ... % cost
    ...% instances periods... % trend
    ... % 1 ord
    cos(1*2*pi/Td*instances) sin(1*2*pi/Td*instances)...
    cos(1*2*pi/Ty*periods) sin(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    ... % 2 ord
    cos(2*2*pi/Td*instances) sin(2*2*pi/Td*instances)... 
    cos(2*2*pi/Ty*periods) sin(2*2*pi/Ty*periods) ...
    cos(2*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(2*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(2*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(2*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)...
    ...% 3 ord
    % cos(3*2*pi/Td*instances) sin(3*2*pi/Td*instances)...
    % cos(3*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    % cos(3*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    % cos(3*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)...
    % cos(3*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
    ...% 4 ord
    % cos(4*2*pi/Td*instances) sin(4*2*pi/Td*instances)...   
    % cos(4*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    % cos(4*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    % cos(4*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)... 
    % cos(4*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
];

data.Load=data.Generation;
tests_2d_w(data, phifun, weigths, "Solar Generation (+)", "Generation(MWh)", true, true);