% Residential Load: linear regression (fourier) Biperiodic model
% Ordine massimo in Quarter: 2

%% Startup
clear 
clc
close all

df = caricaLoad(); % nota: la funzione deve essere aggiunta al path di matlab

data = df(~df.Industrial,:);

pics=true;
write=true;

%% Lasso, backward/forward selection
periods = data.Period;
loads = data.Load;
Ty = 2*365; % (df.Period) yearly period, e sappiamo essere esattamente questo
Td = 2*24; % (df.Instance) daily period.

phifun = @(instances, periods)[
    instances.^0 ... % cost
    ... % 1 ord
    cos(1*2*pi/Td*instances) sin(1*2*pi/Td*instances)...
    cos(1*2*pi/Ty*periods) sin(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    ... % 2 ord
    cos(2*2*pi/Td*instances) sin(2*2*pi/Td*instances)... 
    cos(2*2*pi/Ty*periods) sin(2*2*pi/Ty*periods) ...
    cos(2*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(2*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(2*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(2*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
    cos(1*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(1*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)...
    ...% 3 ord
    cos(3*2*pi/Td*instances) sin(3*2*pi/Td*instances)...
    cos(3*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    cos(3*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(3*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)...
    cos(3*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(3*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
    ...% 4 ord
    cos(4*2*pi/Td*instances) sin(4*2*pi/Td*instances)...   
    cos(4*2*pi/Td*instances).*cos(1*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*sin(1*2*pi/Ty*periods)...
    cos(4*2*pi/Td*instances).*sin(1*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*cos(1*2*pi/Ty*periods)...
    cos(4*2*pi/Td*instances).*cos(2*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*sin(2*2*pi/Ty*periods)... 
    cos(4*2*pi/Td*instances).*sin(2*2*pi/Ty*periods) sin(4*2*pi/Td*instances).*cos(2*2*pi/Ty*periods)...
];

% Lasso, backward/forward stepwise
[mse, nparams, sel] = tests_2d(data, phifun, "Residential Load", "Load (MWh)", write, pics);
